version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: invex-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invexdb
      MYSQL_USER: invex
      MYSQL_PASSWORD: invex
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: ms-invex-test
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/invexdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: invex
      SPRING_DATASOURCE_PASSWORD: invex
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data: